<?php
$title = 'Kontakt';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="myProfile">
	<div class="myProfileImage" style="background-image:url(<?php echo $this->basePath() ?>/img/Foto04.jpg);"></div>
	<div class="myProfileTextfeld1 myProfileText">
		<h3>B&#252;ro</h3> 
		<h5>Rheinestr. 22</h5> 
		<h5>49134 Wallenhorst</h5>
 	</div>
	<div class="myProfileTextfeld2 myProfileText">
		<h3>Kontakt</h3> 
		<h5>Fon 05407/85 99 85</h5>
		<h5>Fax 05407/85 99 84</h5>
		<h5>Stiene@abakon.de</h5>
	</div>
	<div style="clear:both;"></div>
</div>

