<?php
$title = 'Mitarbeiter';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="myProfile">
	<div class="myProfileImage" style="background-image:url(<?php echo $this->basePath() ?>/img/platzhalter.jpg);">
		<!--img src="../img/Foto04.jpg"-->
	</div>
	<div class="myProfileTextfeld1 myProfileText">
		<h5> Dipl.- Ing</h5>
		<h2>Markus Stiene</h2>
		<h4>Prüfingenieur</h4><br />
		<h5>Hans-Böckler-Str. 25<br />
			49134 Wallenhorst<br />
		</h5>
	</div>
	<div class="myProfileTextfeld2 myProfileText">
		<br />
		<br />
		<br />
		<br />

		<h4>Fon 05407/85 99 85<br />
			Fax 05407/85 99 84<br />
			Mobil 0179/ 77 60 865<br />
			Markus-Stiene@web.de
		</h4>

	</div>
</div>
<div style="clear:both;"></div>

<div class="myProfile">
	<div class="myProfileImage" style="background-image:url(<?php echo $this->basePath() ?>/img/platzhalter.jpg);"></div>
	<div class="myProfileTextfeld1 myProfileText">
		<h5> Dipl.- Ing
			<h2>Karl-Heinz Stiene</h2>
			<br />
			<br />

			<h5>Rheinstr. 22<br />
				49134 Wallenhorst<br />
			</h5>
		</div>
		<div class="myProfileTextfeld2 myProfileText">
			<br />
			<br />
			<br />
			<br />

			<h4>Fon 05407/85 99 85<br />
				Fax 05407/85 99 84<br />
				Mobil 0179/ 69 55 058<br />
				Stiene@abakon.de
			</h4>


		</div>

</div>
<div style="clear:both;"></div>

<div class="myProfile">
	<div class="myProfileImage" style="background-image:url(<?php echo $this->basePath() ?>/img/platzhalter.jpg);"></div>
	<div class="myProfileTextfeld1 myProfileText">
		<h5> Dipl.- Ing </h5>
		<h2>Sebastian Sieckermann</h2>
		<h4>Prüfingenieur</h4><br />

		<h5>Staufenbergstr. 34A<br />
			32257 Bünde<br />
		</h5>
	</div>
	<div class="myProfileTextfeld2 myProfileText">
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<h4>Mobil 0177/497 06 76<br />
			sebastian.sieckermann@gmx.de
		</h4>
	</div>
</div>

<div style="clear:both;"></div>

<div class="myProfile">
	<div class="myProfileImage" style="background-image:url(<?php echo $this->basePath() ?>/img/platzhalter.jpg);"></div>
	<div class="myProfileTextfeld1 myProfileText">
		<h5> Dipl.- Ing </h5>
		<h2>Norbert Vehling</h2>
		<h4>Prüfingenieur</h4><br />

	</div>
	<div class="myProfileTextfeld2 myProfileText">
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<h4>Mobil 0170/734 55 84<br />
			norbert.vehling@gmx.de
		</h4>


	</div>

</div>

<div style="clear:both;"></div>

<div class="myProfile">
	<div class="myProfileImage" style="background-image:url(<?php echo $this->basePath() ?>/img/platzhalter.jpg);"></div>
	<div class="myProfileTextfeld1 myProfileText">
		<h5> Dipl.- Ing </h5>
		<h2>Alexander Vehling</h2>
		<h4>Prüfingenieur</h4><br />

	</div>
	<div class="myProfileTextfeld2 myProfileText">
		<br />
		<br />
		<br />
		<br />
		<br />
		<br />
		<h4>Mobil 0170/734 55 84<br />
			alexander.vehling@gmx.de
		</h4>


	</div>

</div>

<div style="clear:both;"></div>