<?php
$title = 'Impressum';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

	


	<h2>Vehling, Stiene & Partner GbR</h2> 
	<h4>KFZ Sachverst&#228;ndige & Prüfingenieure</h4> </br>
	<h5>Rheinestr. 22</h5> 
	<h5>49134 Wallenhorst</h5></br>
	<h5>Fon 05407/85 99 85</h5>
	<h5>Fax 05407/85 99 84</h5>
	<h5>Stiene@abakon.de</h5>
	<h5>Internet: www.vsp.de</h5>
	</br>

	<h4>Pr&#252;fst&#252;tzpunkt</h4>
	<h5>bei Firma "Werner und Wildemann Automobile"</h5> 
	<h5>Bielefelderstr. 50</h5> 
	<h5>49176 Hilter</h5> </br>

	<h4>Gesch&#228;ftsf&#252;hrung</h4>
	<h5>Dipl.- Ing. Karl-Heinz Stiene</h5> 
	</br>
	<h4>Inhaltlich verantwortlich:</h4>
	<h5>Thomas Stiene</h5> 
	<h5>Alena Stryhina</h5>
	</br>
	</br>
	<h4>Haftungsausschluss:</h4> 
	<p>Die enthaltenen Angaben sind nach unserem besten Wissen und Gewissen richtig, vollständig und aktuell. Dennoch wird diese Website, einschließlich des durch sie zugänglich gemachten Inhalts ohne Zusicherung oder Gewährleistungen jeglicher Art, weder ausdrücklich noch stillschweigend, zur Verfügung gestellt. </br>Der Zugang und die Benutzung dieser Website geschieht auf eigene Gefahr des Benutzers. Wir sind nicht verantwortlich und übernehmen keinerlei Haftung für Schäden, die angeblich durch den oder in Verbindung mit dem Zugang und/oder der Benutzung dieser Website aufgetreten sind. Hyperlinks zu den Websites Dritter stellen keine Zustimmung zu deren Inhalt unsererseits dar und wir sind nicht verantwortlich für die Verfügbarkeit oder den Inhalt dieser Websites. Das Herstellen einer Verbindung zu diesen Websites geschieht auf eigene Gefahr des Benutzers.</br>
	Wir weisen darauf hin, dass die Fotos unserer Mitarbeiter gem. § 22 KUG (Recht am eigenen Bild) rechtlich geschützt sind. Insbesondere sind Download, Manipulation, Veröffentlichung oder Vervielfältigung der Bilder nicht erlaubt. Jede Verletzung des Rechts am eigenen Bild kann Ansprüche auf Unterlassung oder Schadensersatz nach sich ziehen.</p>


