<?php
$title = 'Über uns';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<img src="<?php echo $this->basePath() ?>/img/platzhalter1.jpg" class="floatImage">
Das Ingenieurbüro Vehling, Stiene & Partner wurde am 1.1.2007 von den Ingenieuren Norbert Vehling und Karl-Heinz Stiene gegründet, die seit 1982 im Bereich Fahrzeugprüfung und Schadenermittlung tätig sind.

Die amtlichen Fahrzeuguntersuchungen werden im Namen und auf Rechnung der amtlich anerkannten Überwachungsorganisation GTÜ durchgeführt.
<br><br>
<ul>
	<li>Hauptuntersuchunge (HU) nach § 29 StVZO mit integrieter Abgasuntersuchung</li>
	<li>Änderungsabnahme nach § 19  (3)StVZO</li>
	<li>Fahrzeuge mit Gasantrieb GSP, GWP und GAP</li>
	<li>Sicherheitsprüfungen (SP) nach § 29 StVZO</li>
	<li>Untersuchungen nach §§ 41, 42 (2) bzw. 42 (1) BOKraft</li>
	<li>Oldtimergutachtengemäß §23 StVZO zur Erlangung einer H-Zulassung oder eines roten 07er-Kennzeichens</li>
	<li>Feinstaubplaketten</li>
	<li>Tempo 100 Untersuchungen</li>
	<li>Gasprüfungennach DVGW 607Flüssiggasanlagen in privat genutzten Fahrzeugen</li>
</ul>

<h4>Als freiberufliche Sachverständige erstellen wir:</h4>
<ul>
	<li>Unfallschadensgutachten</li>
	<li>Fahrzeugbewertung</li>
	<li>Oldtimerbewertung (Classic Data)</li>
	<li>Gebrauchtwagenbewertung</li>
	<li>Beweissicherungsgutachten</li>
	<li>UVV-Prüfung</li>
</ul>
<div style="clear:both"></div>