<?php
$title = 'Änderungsabnahme';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>Notwendige Sicherheit für Einzelstücke und Exoten</h3>
<img src="<?php echo $this->basePath() ?>/img/platzhalter1.jpg" class="floatImage"><p>Individuell, kreativ und exklusiv: Ein Auto, das es so kein zweites Mal gibt, wünschen sich viele – egal ob Tieferlegung, Alufelgen mit Breitreifen oder der Einsatz von getönten Scheiben. Doch An- und Umbauten erfordern sogenannte Änderungsabnahmen, genauso wie z. B. eine (selbst) eingebaute Zusatzheizung oder ein spezielles, im Ausland gekauftes Sicherheitsgurtsystem, das vom Gesetzgeber eine Bauartengenehmigung voraussetzt. 
<br>Ein Standardmodell kann auf verschiedenstem Wege zum individuellen Schmuckstück werden. Jede Änderung erfordert dabei Genehmigungen, damit die PKWs im Straßenverkehr zugelassen werden und den Insassen die nötige Sicherheit bieten. Dies gilt nicht zuletzt auch für den Import und Export von Kraftfahrzeugen: Auch hier sind entsprechende Gutachten die Voraussetzung, um die Anforderungen der nationalen und internationalen Kraftfahrzeugverordnungen zu erfüllen. 
<br>Egal welches spezielle Anliegen Sie zum Thema Änderungsabnahmen haben, bei uns erhalten Sie immer kompetenten Rat.</p>
<a class="btn btn-default" href="<?php echo $this->url('preise');?>">Kostencalculator</a>
<div style="clear:both"></div>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Nachträgliche Veränderung
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Ordnungsgemäße Eintragung von Änderungen – für Ihre Sicherheit</h4>
		Wollen Sie Ihre eigenen Ideen an Ihrem Fahrzeug verwirklichen? Nur zu – aber sichern Sie sich ab! VSP ist Ihr kompetenter Ansprechpartner bei allen Fragen rund um nachträgliche Veränderungen. Folgende Änderungen bedürfen einer speziellen Änderungsabnahme. Nur wenn die neuen Teile ordnungsgemäß eingebaut sind und nach fachkundiger Prüfung in Ihre Fahrzeugpapiere eintragen wurden, bleibt die Betriebserlaubnis erhalten:
    <ul>
		  <li>Tieferlegung</li>
		  <li>Anbau von Anhängekupplungen und Spoilern</li>
		  <li>Verwendung von Sonderrädern und Sportauspuffanlagen</li>
		  <li>Chiptuning</li>
		  <li>Einsatz anderer Scheinwerfer</li>
		  <li>Anbringen von Folien an Seitenscheiben</li>
    </ul>
		<h4>Für eine erfolgreiche Änderungsabnahme müssen Sie als Fahrzeughalter entsprechende Prüfzeugnisse vorlegen – darunter:</h4>
    <ul>
		  <li>Teilegenehmigungen (ABE, ABG, EG, ECE)</li>
		  <li>Teilegutachten eines akkreditierten Technischen Dienstes</li>
    </ul>
		<br>Bestimmte Änderungen können in der nationalen (ABE) oder internationalen Genehmigung (EG-Typgenehmigung) für das jeweilige Fahrzeug bereits bewilligt sein. 
		<br>Bei fehlenden Prüfzeugnissen oder erloschener Betriebserlaubnis muss ein Gutachten zur Erteilung einer Einzelbetriebserlaubnis erstellt werden. 
		<br>Sind Sie unsicher, wie Sie mit einzelnen Änderungen umgehen müssen? Dann kommen Sie bei uns vorbei – wir helfen Ihnen weiter!
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Bodenfreiheit
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Mindestabstände sorgen für Sicherheit. Welche Regelungen gibt es zur Mindesthöhe? Informieren Sie sich!</h4>
		Explizite Vorschriften für die Bodenfreiheit von Fahrzeugen gibt es in der Straßenverkehrs-Zulassungs-Ordnung (StVZO) nicht. Jedoch gelten die allgemeinen Vorgaben des § 30 StVZO – natürlich in Verbindung mit den allgemein anerkannten Regeln der Technik sowie den heutigen Standards aus Fahrzeugtechnik und Straßenbau. Grundsätzlich ist zu beachten: Fahrzeuge und Verkehrseinrichtungen (in Parkhäusern, Auffahrten, Baustellen) dürfen nicht beschädigt werden – weder beim verkehrsüblichen Fahrbetrieb, noch beim Überfahren einer Bodenwelle, eines Schlagloches, eines abgesenkten Bordsteines oder anderen Hindernissen. 
		<br>Sachverständige Gremien beim Bundesverkehrsministerium schlagen folgende Richtwerte laut VdTÜV-Merkblatt 751 vor: Ein Hindernis von 800 mm Breite und einer Höhe von 110 mm muss mittig überfahren werden können, ohne berührt zu werden. Dieser Orientierungswert gilt für ein tiefer gelegtes Fahrzeug mit vollem Kraftstofftank, welches mit einem Fahrer besetzt ist. Bei diesem Wert kann man davon ausgehen, dass im normalen Straßenverkehr keine Beschädigungen eintreten. 
		<br>Abweichungen sind möglich – jedoch nur in begründeten Einzelfällen. Dann tragen sowohl Fahrer als auch Fahrzeughalter die Verantwortung für den verkehrssicheren Betrieb des Fahrzeugs. Wer zu wenig Abstand zwischen Fahrzeug und Boden einhält, riskiert eine beschädigte Ölwanne – und austretendes Öl auf der Fahrbahn kann zu einer unmittelbaren Gefährdung anderer Verkehrsteilnehmer führen. Sicherheit ist also oberstes Gebot – kontaktieren Sie Ihre DEKRA Spezialisten! 
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Beleuchtung
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Weniger ist oft mehr</h4>
		Unzulässig oder nicht korrekt angebrachte Beleuchtungseinrichtungen sind eine Gefahr im Straßenverkehr – denn sie können erhebliche Veränderungen des zulässigen Signalbildes und somit Fehleinschätzungen zur Folge haben. Fahrzeughalter solcher Beleuchtungseinrichtungen müssen daher bei Polizei-Kontrollen mit Verwarn- oder Bußgeldern rechnen. Des Weiteren gelten unzulässige, falsch oder in inkorrekter Anzahl verbaute lichttechnische Einrichtungen als sogenannte erhebliche Mängel (EM) bei der Hauptuntersuchung – hier kann die Prüfplakette nicht zugeteilt werden. 
		<br>Kosten und Aufwand können Sie nur dann vermeiden, wenn alle der nicht zulässigen und falsch angebrachten leuchtenden Einrichtungen an oder im Fahrzeug entfernt werden. Dies gilt auch dann, wenn die Leuchten nicht funktionstüchtig sind. 
		<br>
		<h4>Betroffen sind hier: </h4>
    <ul>
		  <li>Beleuchtete Firmenschilder</li>
		  <li>Gelbe Leuchten / Rückstrahler, nach vorne wirkend</li>
		  <li>Beleuchtete „Michelin-Männchen“</li>
		  <li>Namensschilder / Symbole mit (umlaufendem) Licht</li>
		  <li>Punktstrahler mit blauem oder andersfarbigem Licht</li>
    </ul>
		<br>Mit unserer Informationsbroschüre „Lichttechnische Einrichtungen an Kraftfahrzeugen und deren Anhängern“ sind Sie auf der sicheren Seite, wenn es um das Thema Beleuchtung geht – zudem stehen Ihnen unsere VSP-Prüfingenieure bei Fragen jederzeit zur Verfügung. 
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Scheibenfolien
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
		<h4>Freie Sicht für den Fahrer ist ein Muss</h4>
		Folien auf Sicherheitsglasscheiben gehören gemäß § 22a der StVZO zu jenen Ausstattungen, die ausschließlich in einer amtlich genehmigten Bauart realisiert werden dürfen. Welche Besonderheiten und Bedingungen Sie bei glasklaren oder getönten Folien beachten müssen, erfahren Sie hier: 
		<h4>Glasklare Folien</h4>
		Glasklare Folien sind zwar an der Innenseite von Fahrzeugscheiben zulässig, allerdings nicht an der Windschutzscheibe und nicht an den vorderen Seitenscheiben (innerhalb des 180°-Sichtfeldes des Fahrers).  Bei den vorderen Seitenscheiben sind Ausnahmen möglich, wenn in der Allgemeinen Bauartgenehmigung (ABG) der ausgewiesene Verwendungsbereich ausdrücklich dafür zugelassen ist. Eine Anbringung an getönten vorderen Seitenscheiben ist jedoch generell verboten. Auch darf insgesamt ein bestimmtes Maß der Scheibendicke nicht überschritten werden. 
		<br>Gerade beim Anbringen von Folien an den vorderen Seitenscheiben muss eine Änderungsabnahme gemäß § 19 (3) StVZO durchgeführt werden – nur so können alle Bedingungen eingehalten werden. Die Gültigkeit der entsprechenden ABG ist hierfür von einer Anbauabnahme abhängig. 
		<h4>Getönte Folien</h4>
		Getönte Folien sind an der Innenseite von Fahrzeugscheiben zulässig, die nicht für die Sicht des Fahrzeugführers von Bedeutung sind. Ausgenommen sind deshalb Scheiben im nach vorne gerichteten 180°-Sichtfeld des Fahrers (Windschutzscheibe, vordere Seitenscheiben) sowie Notfenster. Bei der Anbringung an der Heckscheibe wird zudem ein zweiter Außenspiegel gefordert. 
		<br>Ob glasklare oder getönte Folien – die VSP- Experten wissen Bescheid und stehen Ihnen bei Fragen mit Rat und Tat zur Seite. Kontaktieren Sie uns!
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
          Bauartgenehmigung für Fahrzeugteile
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Sicherheit wird durch Prüfzeichen garantiert</h4>
		Einzeln gefertigte oder aus dem Ausland importierte Fahrzeugteile müssen auf ihre Verwendbarkeit hin überprüft werden – dies gilt besonders für solche Fahrzeugteile, die gemäß § 22 a StVZO in amtlich genehmigter Bauart ausgeführt sind und ein Prüfzeichen haben müssen. Dazu gehören:
    <ul>
		  <li>Anhängekupplungen</li>
		  <li>Zusatzheizungen</li>
		  <li>Scheiben aus Sicherheitsglas und Folien</li>
		  <li>Warndreiecke und Warnleuchten</li>
		  <li>Diverse Leuchten und Scheinwerfer</li>
		  <li>Sicherheitsgurte und Rückhalteeinrichtungen</li>
    </ul>
		<br>Die Bauartgenehmigung wird nach der Begutachtung durch einen amtlich anerkannten Sachverständigen von der Zulassungsstelle erteilt – erst dann ist das entsprechende Teil für den Anbau am Fahrzeug freigegeben. Solche Begutachtungen dürfen ausschließlich von sogenannten aaS (amtlich anerkannten Sachverständigen) der Technischen Prüfstelle (TP) ausgestellt werden. 
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          Gasanlagen in PKW
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Pflicht-Überprüfung sorgt für nötige Sicherheit</h4>
		Die steigenden Kraftstoffpreise machen eine Nachrüstung von Gasanlagen in Kraftfahrzeugen für Verbraucher immer attraktiver. Dabei stehen gleich zwei Varianten zur Auswahl: Es wird zwischen Systemen mit Flüssiggas (LPG - Liquefied Petroleum Gas) und komprimiertem Erdgas (CNG - Compressed Natural Gas) unterschieden – eine fachgemäße Begutachtung, die sogenannte Gassystemeinbauprüfung (GSP), ist bei beiden Möglichkeiten unerlässlich. Hier werden der korrekte Einbau, die Sicherheitsfunktionen und die Gasdichtheit überprüft.
		<br>
		<br>Die Gassystemeinbauprüfung kann in allen DEKRA Prüfstellen erfolgen. Sofern bereits eine Genehmigung nach ECE-R 115 vorliegt, kann nach der GSP direkt die Korrektur der Fahrzeugpapiere bei der Zulassungsbehörde vorgenommen werden. Liegt keine solche Genehmigung vor, muss zusätzlich ein amtlich anerkannter Sachverständiger (aaS) einer Technischen Prüfstelle (TP) eine Einzelbegutachtung nach §21 StVZO vornehmen und dabei unter anderem auch prüfen, ob eine bestimmte Gasanlage für Ihr Fahrzeug zulässig ist und ob diese vorschriftsmäßig eingestellt wurde.
		<br>
		<br>Bei Fragen rund um das Thema Gasanlagen stehen Ihnen die VSP- Experten natürlich jederzeit gerne mit Rat und Tat zur Seite – kontaktieren Sie uns!
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSeven">
          Einzelbetriebserlaubnis
        </a>
      </h4>
    </div>
    <div id="collapseSeven" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Check bei Technischer Prüfstelle ist Pflicht</h4>
		Gestalten Sie Ihr Fahrzeug lieber selbst und nach Ihren persönlichen Vorstellungen? Dann ist ein spezifisches Gutachten, eine sogenannte Einzelbetriebserlaubnis (EBE), Pflicht, um die Sicherheit für Fahrer und andere Verkehrsteilnehmer zu gewährleisten. Laut § 21 StVZO ist solch eine Einzelbetriebserlaubnis zur Zulassung eines Fahrzeuges am öffentlichen Straßenverkehr in folgenden Fällen erforderlich: 
    <ul>
		  <li>Einzelanfertigung von Fahrzeugen</li>
		  <li>In Kleinserie produzierte Fahrzeuge</li>
		  <li>Aus dem Ausland importierte Fahrzeuge ohne EG-Typgenehmigung</li>
		  <li>Fahrzeuge mit umfangreichen baulichen Veränderungen nach individuellen Vorstellungen</li>
		  <li>Fahrzeuge mit Umbauten für besondere Einsatzzwecke</li>
		  <li>Fahrzeuge, deren Betriebserlaubnis erloschen ist, da sie länger als 18 Monate durch die Zulassungsstelle abgemeldet waren</li>
    </ul>

		          <h4>Auto wird zum Pkw mit Lkw-Zulassung</h4>
				Wer sein Personenkraftfahrzeug zu einem Pkw mit Lkw-Zulassung umrüsten lässt, muss gewährleisten, dass tatsächlich und dauerhaft die Eignung als Fahrzeug zum Gütertransport gegeben ist. Dies umfasst: 
        <ul>
				  <li>Entsprechendes Ladevolumen bzw. entsprechende Laderaumlänge</li>
				  <li>Unbrauchbar gemachte Sitz- und Sicherheitsgurtverankerungen</li>
				  <li>Eingesetzte Bleche anstelle der Seitenscheiben hinten (je nach zuständigem Finanzamt)</li>
        </ul>
				In Sachen steuerlicher Anerkennung der Klassifizierung als Lkw entscheidet das Finanzamt. Dieses sollten Sie auf jeden Fall zuvor konsultieren, wenn der Umbau aus steuerrechtlichen Gründen durchgeführt wird.
		          <h4>Auto wird zur Wohnung auf Rädern</h4>
				Das Merkblatt des VdTÜV (Nr. 740) regelt die Anforderungen an Wohnwagen bzw. Wohnmobile. Zu den Kriterien gehören: 
        <ul>
				  <li>Mindestausstattung für den Wohnteil (Sitz- und Schlafgelegenheit, Küche, Tisch, Stauraum)</li>
				  <li>Feste Montage von Einbauten, Heizung und Belüftung</li>
        </ul>
				Hierbei gilt es zu beachten, dass der Wohnteil den überwiegenden Teil des Fahrzeugs einnehmen und den Eindruck eines für Wohnzwecke geeigneten Raumes hervorrufen muss. In Sachen Ausstattung muss der Wohnteil so gestaltet sein, dass auch bei Unfällen die Gefahr oder das Ausmaß von Verletzungen möglichst gering gehalten wird.
		          <h4>Mehr Reichweite durch Zusatztank</h4>
				Ein Zusatztank schafft mehr Reichweite – der Einbau unterliegt jedoch den gleichen Vorschriften und Anforderungen, die auch für den serienmäßigen Tank gelten. Diese Anforderungen gelten für:
        <ul>
				  <li>Den Tank selbst (Material, Festigkeit, Überdruckbeständigkeit)</li>
				  <li>Dessen Anbringungsort (innerhalb oder außerhalb des Insassenraumes mit entsprechenden Zusatzforderungen wie Trennwand)</li>
				  <li>Dessen Befestigung und deren Festigkeit (bei Frontal- und Heckaufprall)</li>
				  <li>Den Anschluss der Leitungen und deren Verbindung untereinander (feste und flexible Leitungen)</li>
				  <li>Zur Vermeidung elektrostatischer Aufladungen</li>
        </ul>
				Die EG-Richtlinien sowie § 21 der StVZO sind Basis unserer Prüfungen: Fällt ein jeweiliges Gutachten positiv aus, so erteilt die Zulassungsstelle anschließend eine Einzelbetriebserlaubnis (EBE) durch Ausstellen des Fahrzeugscheins.
				<br>
				<br>Ausschließlich amtlich anerkannte Sachverständigen (aaS) der Technischen Prüfstelle (TP) dürfen Gutachten zur Erteilung einer Einzelbetriebserlaubnis erstellen. Mit der Aufgabe der TP ist in Berlin und in den neuen Bundesländern VSP beauftragt – bei Fragen rund um Themen wie Umrüstung, Begutachtung und beabsichtigte Änderungen helfen Ihnen unsere Ansprechpartner gerne weiter!
      </div>
    </div>
  </div>
</div>




