<?php
$title = 'Oldtimer-Gutachten';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>Das VSP- Leistungsspektrum für Young- und Oldtimer</h3>
<img src="<?php echo $this->basePath() ?>/img/platzhalter1.jpg" class="floatImage"><p>Young- und Oldtimer bedürfen besonderer Pflege und Zuwendung – denn jeder Fahrzeugklassiker ist für sich etwas ganz besonderes. Oldtimer-Freunde können sich dabei auf den VSP-Service verlassen. Mit unserem großen Leistungsspektrum unterstützen wir Sie bei allen Fragen rund um Ihren persönlichen Liebling – von Oldtimer-Gutachten für das H-Kennzeichen, die kompetente Begleitung von Restaurierung und Reparatur, die Prüfdokumentation für das rote 07-Kennzeichen, bis hin zu Wert- oder Schadengutachten und Hauptuntersuchung. So sind nicht nur die Young- und Oldtimer, sondern auch ihre Liebhaber bei VSP in besten Händen. </p>
<a class="btn btn-default" href="<?php echo $this->url('preise');?>">Kostencalculator</a>
<div style="clear:both"></div>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Zulassung
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Das richtige Kennzeichen für die Zulassung Ihres Oldtimers</h4>
		<br>Wenn Sie einen Oldtimer besitzen, der über 30 Jahre alt ist, dann können Sie zwei Kennzeichen für eine Zulassung beantragen: das H-Kennzeichen oder das rote 07er-Kennzeichen. 
		<br>Oldtimer-Besitzer, die ihr Fahrzeug jedoch ohne Einschränkungen im Straßenverkehr nutzen und zudem einen geringen Jahressteuersatz zahlen möchten, benötigen das H-Kennzeichen. Dieses erhalten Sie auf Antrag von der Zulassungsstelle. 
		<br>
		<h4>Die Voraussetzungen für das H-Kennzeichen sind:</h4>
    <ul>
  		<li>Gültige Betriebserlaubnis oder Gutachten nach §21 StVZO (Einzelbetriebserlaubnis)</li>
  		<li>Begutachtung nach §23 StVZO (Auszeichnung zum „kraftfahrzeugtechnischen Kulturgut“ – dieses Gutachten erhalten Sie auch von unseren VSP-Experten)</li>
  		<li>Gepflegter Zustand des Oldtimers</li>
  		<li>Ursprünglicher Zustand oder mit Originalteilen restauriert (zeittypische Änderungen sind möglich)</li>
    </ul>
		<br>Falls Sie jedoch Ihr Fahrzeug ausschließlich bei Oldtimer-Veranstaltungen einsetzen möchten, benötigen Sie das rote 07er-Kennzeichen (amtliches Kennzeichen und Betriebserlaubnis sind nicht notwendig). Auch dieses Kennzeichen erhalten Sie auf Antrag von der Zulassungsstelle. Ihr Vorteil dabei: Das Wechselkennzeichen ist für mehrere Fahrzeuge verwendbar. 
		<br>
		<h4>Die Voraussetzungen für das 07er-Kennzeichen sind:</h4>
    <ul>
		  <li>Nachweis der Verkehrssicherheit des Oldtimers (unsere VSP- Experten überprüfen dies in einer detaillierten Prüfdokumentation)</li>
		  <li>Einwilligung der örtlichen Zulassungsstelle </li>
    </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Schadengutachten
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <h4>Objektives Experten Know-how im Ernstfall unverzichtbar</h4>
		<br>Sollte Ihr Oldtimer tatsächlich einmal beschädigt werden, stehen wir Ihnen als Sachverständige zur Verfügung und informieren Sie über die weitere Vorgehensweise in einem Schadenfall. 
		<br>Entsteht ein Schaden bei einem nicht von Ihnen verursachten Verkehrsunfall, müssen die Kosten der Unfallabwicklung von der Versicherung des Unfallverursachers beglichen werden (ein sogenannter Haftpflichtschaden tritt ein). Darunter fallen etwa die Kosten für einen Rechtsanwalt sowie die Reparatur des beschädigten Fahrzeuges selbst. Unsere VSP-Experten helfen Ihnen, Ihren Anspruch geltend zu machen. 
		<br>Als objektive Sachverständige ermitteln und dokumentieren unsere Experten den tatsächlichen Schadenzustand Ihres Fahrzeuges. Zudem beraten wir Sie auf Grundlage des VSP- Schadengutachtens über etwaige Reparaturkosten, mögliche Wertminderungen oder den Wiederbeschaffungswert Ihres Oldtimers.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          Wertgutachten
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
		<h4>Klarheit und Sicherheit mit dem Oldtimer-Wertgutachten</h4>
		<br>Oldtimer sind für ihre Besitzer vor allem Liebhaber-Fahrzeuge. Um aber den tatsächlichen Marktwert Ihres Oldtimers zu erfahren, erstellen wir für Sie ein manuelles Wertgutachten. 
		<br>
		<br>In diesem Gutachten wird das Fahrzeug in allen Einzelheiten beschrieben: Neben der Auflistung sämtlicher technischer Daten erfolgt eine detaillierte Zustandsbeschreibung aller Baugruppen. Wurden Restaurierungen und Umbauten vorgenommen, so werden auch diese in das Gutachten integriert.
		<br>
		<br>Nach einer umfangreichen Marktrecherche können wir den realistischen Marktwert sowie den Wiederbeschaffungs- oder den Wiederherstellungswert Ihres Oldtimers feststellen. Mit dem Oldtimer Wertgutachten erhalten Sie eine genaue Dokumentation des Fahrzeugzustandes, was Ihnen eine sichere Grundlage für Kauf, Verkauf und Versicherung bietet. Zusätzlich empfehlen wir Ihnen, in regelmäßigen Abständen eine Aktualisierung der Wertfindung für Ihr Fahrzeug vorzunehmen, da sich der Oldtimermarkt in ständiger Bewegung befindet.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Wiederaufbauwertgutachten
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
		<h4>Lückenlose Zustandsdokumentation Ihres Oldtimers</h4>
		<br>Einen Oldtimer nach einer kompletten Restaurierung zu bewerten, stellt oft ein kompliziertes Unterfangen dar. Mit dem VSP-Wiederaufbauwertgutachten garantieren wir, dass unsere Oldtimer-Experten den Wert der Arbeit unabhängig beurteilen und den Qualitätsmaßstab nach außen hin exakt dokumentieren. 
		<br>Nach Sichtung der entsprechenden Unterlagen geben unsere VSP- Experten Empfehlungen zum Erhalt originaler Teile. Darüber hinaus fotografieren sie in regelmäßigen Abständen die Arbeiten beim Wiederaufbau, so dass die Restaurierung sogar nach vielen Jahren nachvollziehbar bleibt. Diese Gutachten ziehen Spezialversicherer gerne als Grundlage für die spätere Absicherung heran. 
		<br>Darüber hinaus bieten viele Versicherungen an, den Klassiker bis zum Wiederherstellungswert zu versichern. Wurde beispielsweise das Fahrzeug innerhalb eines Kaskoschadens beschädigt, so besteht die Möglichkeit, bis zu diesem Wert – also auch über den versicherten Marktwert hinaus – den Oldtimer wieder aufzubauen. Sogar bei Totalverlust (Brand, Diebstahl) wird ein Anspruch auf den Wiederaufbau auf Basis eines entsprechenden Fahrzeugtyps geltend– oder alternativ eine Entschädigung zum versicherten Marktwert.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFive">
          Gutachten zur Kaufberatung
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse">
      <div class="panel-body">
		<h4>Das individuelle Gutachten zur Zustandsprüfung & Werteinschätzung</h4>
		<br>Für Oldtimerbesitzer bietet das VSP- Gutachten zur Kaufberatung ein ideales Zeugnis, das den Zustand Ihres Fahrzeuges umfassend und neutral dokumentiert. In einer detaillierten Zustandsaufnahme ermitteln wir die Originalität, die vorgenommenen Restaurierung und den aktuellen Marktwert Ihres Oldtimers. 
		<br>Dabei stufen unsere VSP- Experten die einzelnen Baugruppen entsprechend der gängigen Zuständigkeitskriterien nach IfS-Standard ein und dokumentieren zudem mit Fotos den Zustand Ihres Fahrzeuges. Der Umfang der Zustandsprüfung wird dabei individuell auf Ihre Wünsche abgestimmt. Schließlich erhalten Sie nach der Auswertung der Dokumente eine Gesamtnote für Ihren Oldtimer. 
		<br>Sollten zu späterer Zeit weitere Restaurierungen an Ihrem Fahrzeug vorgenommen werden, empfehlen wir erneut eine Zustandsdokumentation mit Benotung. Das Ergebnis wird den bereits bestehenden Gutachten – falls vorhanden – zugeordnet, sodass für Ihr Fahrzeug stets eine lückenlose Dokumentation verfügbar ist.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseSix">
          Oldtimer-Sachverständige
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse">
      <div class="panel-body">
		<h4>Wir wissen Ihre Schätzchen zu schätzen</h4>
		<br>Die Affinität zu Klassik-Fahrzeugen hat bei  VSP-  Tradition: So ist ein Exemplar des sogenannten Kommissbrots, ein Hanomag 2/10, als erster  VSP-  Dienstwagen noch heute auf Messen und Ausstellungen präsent. Der Oldtimer versinnbildlicht die Geschichte des Unternehmens, welches 1925 in Berlin als Deutscher Kraftfahrzeug-Überwachungsverein gegründet wurde. 
      </div>
    </div>
  </div>
</div>