<?php
$title = 'Schadengutachten';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>Höchste Sicherheit und Qualität für den Ernstfall</h3>
<img src="<?php echo $this->basePath() ?>/img/platzhalter1.jpg" class="floatImage"><p>Nach einem Verkehrsunfall ist eine präzise und sorgfältige Beurteilung der Fahrzeugschäden entscheidend. Dabei können Sie sich auf das Know-how der VSP- Experten verlassen: Wir ermitteln umfassend und neutral die Kosten für die Reparatur Ihres Fahrzeugs. Das erstellte Gutachten dient dabei vor allem als Regulierungsgrundlage – und macht sich so für Sie direkt bezahlt, denn Sie können sicher sein, dass alle für die Beweissicherung und Schadenregulierung relevanten Fakten berücksichtigt wurden. 
<br>Aufgrund jahrelanger Erfahrung ist VSP Ihr perfekter Partner bei der Schadenbeurteilung – von der Ermittlung der Schadenhöhe über die Beweissicherung und Dokumentation von Wertminderungen bis hin zur Schadenregulierung. Wir stehen Ihnen mit Rat und Tat zur Seite.</p>
<a class="btn btn-default" href="<?php echo $this->url('preise');?>">Kostencalculator</a>
<div style="clear:both"></div>
