<?php
$title = 'Sicherheitsprüfung';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h3>Vertrauen ist gut – Gutachten ist besser</h3>
<img src="<?php echo $this->basePath() ?>/img/platzhalter1.jpg" class="floatImage"><p>Beim An- oder Verkauf von gebrauchten Fahrzeugen sollten Sie den Wert des Fahrzeuges im Istzustand kennen. Unsere VSP-Spezialisten erfassen für Sie alle relevanten Fahrzeugdetails und errechnen mit modernster Software-Unterstützung den aktuellen Wert von Autos, Transportern bis 3,5 t (ohne Sonderaufbauten) sowie von Motorrädern und Geländewagen. Dabei werden Innen-, Motor- und Kofferraum sowie die gesamte Karosserie, inklusive Unterseite mit Fahrwerk einer demontagefreien Sichtprüfung unterzogen. Außerdem prüfen wir (soweit möglich)die Funktion von Ausstattungsteilen und führen eine kurze Fahrprobe durch. Unsere geschulten Sachverständigen bleiben stets auf dem neuesten Stand und haben auch die Marktentwicklung fest im Blick, so dass sie auch kurzfristig auftretende Marktschwankungen in der Dokumentation berücksichtigen.  
<br>
<br>
<h4>Folgende Faktoren dokumentieren wir bei der Wertermittlung von gebrauchten Fahrzeugen:</h4>
<ul>
	<li>Allgemeine Fahrzeugdaten (wie Ausführung, Erstzulassung, Laufleistung)</li>
	<li>Serien- und Sonderausstattung</li>
	<li>Werterhöhende Faktoren (wie AT-Aggregate, wertsteigernde Reparaturen)</li>
	<li>Notwendige Reparaturen (wie Beschädigungen, Verschleiß von sicherheitsrelevanten und sonstigen Teilen, fehlende Inspektionen)</li>
	<li>Fehlende Teile (wie aus- oder abgebautes Serienzubehör, unvollständiges Bordwerkzeug)</li>
	<li>Wertminderung aus Vorschäden (reparierte Unfallschäden)</li>
</ul>
<br>
<h4>EDV-Zustandsbericht dokumentiert Minderwerte:</h4>
<br>Genügt allein die Dokumentation der am Fahrzeug vorhandenen Mängel und die daraus resultierenden Minderwerte, so ermitteln unsere VSP-Experten diesen Wert in einem EDV-Zustandsbericht. Weicht der Zustand eines Fahrzeugs aufgrund beschädigter Teile oder Unfallschäden vom Standard ab, so klären wir, in welchem Umfang notwendige Reparaturen oder vorherige Unfälle eine Wertminderung verursachten, und weisen diese explizit aus.
<br>Egal, ob Ankauf, Verkauf oder versicherungsbedingt – mit Fahrzeugbewertungen kennen wir uns bestens aus. Vertrauen Sie auf die Erfahrung der VSP-Experten und kontaktieren Sie uns!</p>
<a class="btn btn-default" href="<?php echo $this->url('preise');?>">Kostencalculator</a>
<div style="clear:both"></div>