<?php
$title = 'Registrieren';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<h4><?php echo $this->error; ?></h4>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('login', array('action' => 'registration')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('username')->setAttribute('class', 'form-control'));
echo $this->formRow($form->get('email')->setAttribute('class', 'form-control'));
echo $this->formRow($form->get('name')->setAttribute('class', 'form-control'));
echo $this->formRow($form->get('surname')->setAttribute('class', 'form-control'));
echo $this->formRow($form->get('password')->setAttribute('class', 'form-control'));
echo $this->formRow($form->get('confirmPassword')->setAttribute('class', 'form-control'));
echo '<br/>';
echo $this->formSubmit($form->get('submit')->setAttribute('class', 'form-control btn-default'));
echo $this->formElement($this->form->get('csrf'));
echo $this->form()->closeTag();
?>
<br>
<a class="btn btn-default" href="<?php echo $this->url('login',array('action' => 'login'));?>">Zurück</a>