<?php
$title = 'Alle Preise im Überblick';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div id="myTableFrame">
	<table class="myTable">
		<tr>
			<th             colspan="2"><fett>Entgelte in €</fett><br/>inkl. 19% MwSt.<br/><fett>gültig ab 1. Februar 2014</fett></th>
			<th             colspan="5">§ 29 StVZO<br/><fett>HU</fett> <upper>1)</upper><br/>(Hauptuntersuchung)</th>
			<th             colspan="2">§ 29 StVZO<br/><fett>SP</fett> <upper>1)</upper><br/>(Sicherheutsüberprüfung)</th>
			<th             colspan="5">§ 19(3) StVZO<br/><fett>Änderungen am Fahrzeug</fett><br/>(Änderungsabnahmen)</th>
			<th             colspan="2">§ 23 StVZO<br/><fett>Oldtimer-Gutachten</fett></th>
		</tr>
		<tr>
			<td rowspan="3" class="myTableAlignLeft"><fett>Fahrzeugart</fett></td>
			<td rowspan="3"            >zulässige<br/>Ges-Masse<br/>(Gewicht)</td>
			<td             colspan="3"><fett>Erstuntersuchung</fett> <upper>2)</upper></td>
			<td             colspan="2"><fett>Nachprüfung</fett></td>
			<td rowspan="3"            >Erst-<br/>unter-<br/>suchung</td>
			<td rowspan="3"            >Nach-<br/>unter-<br/>suchung</td>
			<td rowspan="3"            >einfach</td>
			<td rowspan="3"            >mittel</td>
			<td rowspan="3"            >umfang-<br/>reich</td>
			<td rowspan="3"            >Nach-<br/>unter-<br/>suchung</td>
			<td rowspan="3"            ><div class="myTableVertical">Zuschlag<br/>pro &frac14; Std.</div></td>
			<td rowspan="2" colspan="2"><fett>Ersterstattung</fett><br/>(H- od. 07er-Kennzeichen)</td>
		</tr>
		<tr>
			<td rowspan="2"            ><fett>ohne UMA</fett> <upper>*)</upper><br/>(UMA liegt vor)</td>
			<td             colspan="2"><fett>inklusive UMA</fett> <upper>*)</upper></td>
			<td rowspan="2"            >Nachunter-<br/>suchung</td>
			<td rowspan="2"            ><div class="myTableVertical">Nach-<br/>kontrolle</div></td>
		</tr>
		<tr>
			<td>ohne<br/>Abgasstrom-<br/>messung</td>
			<td>mit<br/>Abgasstrom-<br/>messung</td>
			<td>ohne<br/>UMA <upper>*)</upper></td>
			<td>inkl.<br/>UMA <upper>*)</upper></td>
		</tr>
		<tr>
			<td              colspan="2" class="myTableAlignLeft"><fett>Kraftrad</fett> (EZ vor 1.1.1989)</td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('hu','Kraftrad', '', 'a')['preis']; ?></td>
			<td              colspan="2" class="myTableCrossed"></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('hu','Kraftrad', '', 'd')['preis']; ?></td>
			<td rowspan="10"            ><div class="myTableVertical">(einfach)<?php echo $gtueData->getPreis('hu','Kraftrad', '', 'e')['preis']; ?><br/>(umfangreich)<?php echo $gtueData->getPreis('hu','Kraftrad', '', 'f')['preis']; ?></div></td>
			<td rowspan="2"  colspan="2" class="myTableCrossed"></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'a')['preis']; ?></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'b')['preis']; ?></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'c')['preis']; ?></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'd')['preis']; ?></td>
			<td rowspan="25"            ><div class="myTableVertical"><?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'e')['preis']; ?></div></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('oldtimer','Kraftrad', '', 'a')['preis']; ?></td>
			<td rowspan="2"  class="myTableCrossed"></td>
		</tr>
		<tr>
			<td              colspan="2" class="myTableAlignLeft"><fett>Krad</fett> (EZ ab 1.1.89) <fett>u. EU-Quad/-Trike</fett><upper>**)</upper></td>
			<td              colspan="2"><?php echo $gtueData->getPreis('hu','Krad', '', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td class="myTableAlignLeft"><fett>Pkw</fett> <upper>3)</upper></td>
			<td                         ><fett>bis 3,5 t</fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('hu','Pkw', 'bis 3,5 t', 'a')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('hu','Pkw', 'bis 3,5 t', 'b')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('hu','Pkw', 'bis 3,5 t', 'c')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('hu','Pkw', 'bis 3,5 t', 'd')['preis']; ?></fett></td>
			<td              colspan="2" class="myTableCrossed"></td>
			<td                         ><fett><?php echo $gtueData->getPreis('aenderung','Pkw', 'bis 3,5 t', 'a')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('aenderung','Pkw', 'bis 3,5 t', 'b')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('aenderung','Pkw', 'bis 3,5 t', 'c')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('aenderung','Pkw', 'bis 3,5 t', 'd')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('oldtimer','Pkw', 'bis 3,5 t', 'a')['preis']; ?></fett></td>
			<td                         ><fett><?php echo $gtueData->getPreis('oldtimer','Pkw', 'bis 3,5 t', 'b')['preis']; ?></fett></td>

		</tr>
		<tr>
			<td rowspan="7" class="myTableAlignLeft">Lkw, Zugmaschine,<br/>Sattelzugmaschine,<br/>Arbeitsmaschine, KOM<br/>und sonstige Kraftfahr-<br/>zeuge</td>
			<td                         >bis 3,5 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;3,5 bis 7,5 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'c')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'c')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;7,5 bis 12,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
			<td rowspan="5"             ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;12,0 bis 18,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>12,0 bis 18,0 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;18,0 bis 28,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>18,0 bis 28,0 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;28,0 bis 32,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>28,0 bis 32,0 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >über 32,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'über 32,0 t', 'b')['preis']; ?></td>
		</tr>
		<tr>
			<td rowspan="3" class="myTableAlignLeft">Lof.-ZM <upper>4)5)</upper> bis 40 km/h</td>
			<td                         >bis 7,5 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="15" colspan="2" class="myTableCrossed"></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'd')['preis']; ?></td>
			<td rowspan="15"            ><div class="myTableVertical"><?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'm')['preis']; ?></div></td>
			<td rowspan="3"  colspan="2" class="myTableCrossed"></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'b')['preis']; ?></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'c')['preis']; ?></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'd')['preis']; ?></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('oldtimer','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="15" class="myTableCrossed"></td>
		</tr>
		<tr>
			<td                         >&gt;7,5 bis 12,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >über 12,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td rowspan="4" class="myTableAlignLeft">Lof.-ZM <upper>5)</upper> üb. 40 km/h</td>
			<td                         >bis 7,5 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="4"             ><?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'd')['preis']; ?></td>
			<td             colspan="2" class="myTableCrossed"></td>
			<td rowspan="4"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="4"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'b')['preis']; ?></td>
			<td rowspan="4"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'c')['preis']; ?></td>
			<td rowspan="4"             ><?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;7,5 bis 18,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?></td>
			<td rowspan="3"             ><?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;18,0 bis 32,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >über 32,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td class="myTableAlignLeft">Anh. ohne Bremse</td>
			<td                         >bis 0,75 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger ohne Bremse', 'bis 0,75 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger ohne Bremse', 'bis 0,75 t', 'd')['preis']; ?></td>
			<td rowspan="3"  colspan="2" class="myTableCrossed"></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger ohne Bremse', 'bis 0,75 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td rowspan="7" class="myTableAlignLeft">Anhänger m. Bremse,<br/>Starrdeichselanhaenger<br/>od. Sattelanhaenger <upper>6)</upper><br/>m.Bremse</td>
			<td                         >bis 3,5 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'bis 3,5 t', 'a')['preis']; ?></td>
			<td rowspan="2"             ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'bis 3,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'c')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', 'bis 3,5 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;3,5 bis 7,5 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'b')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'c')['preis']; ?></td>
			<td rowspan="6"             ><?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;7,5 bis 12,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
			<td rowspan="5"             ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'd')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
			<td rowspan="5"             ><?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'b')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;12,0 bis 18,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;18,0 bis 28,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >&gt;28,0 bis 32,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?></td>
		</tr>
		<tr>
			<td                         >über 32,0 t</td>
			<td                         ><?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?></td>
			<td                         ><?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?></td>
		</tr>
	</table>
</div>

<div id="bemerkungen">
	<h4>Bemerkungen:</h4>
	<upper>1)</upper> Bei Kombination von HU und SP berechnet sich das Prüfentgelt wie folgt: HU + (0,6 * SP)<br>
	<upper>2)</upper> Inkl. 1,19 € nach Anl. VIIIa Nr.1 zu §29 StVZO für die Datenbereitstellung durch die FSD GmbH<br>
					  Bei Überschreiten d.Vorführtermins um mehr als zwei Monate, erhöht sich das Prüfentgelt<br>
					  um 20% des HU-Entgelts (ohne UMA)<br>
	<upper>3)</upper> Bei Pkw mit zul. Ges.-Masse üb. 3,5 t gilt das Entgelt der Nfz-Klasse mit zGM >3,5 bis 7,5<br>
	<upper>4)</upper> Bei HU-Entgelten gilt für Lof-ZM die Masse, die von der/den gebremsten Achse/n auf den<br>
					  Boden übertragen werden darf.<br>
	<upper>5)</upper> Zuschlag für Überprüfen der Druckluftanlage am Fahrzeug 10,00 <br>
	<upper>6)</upper> Bei HU- und SP-Entgelten gitl für Sattelanhängern die Masse, die von der/den Radachse/n auf<br>
					  den Boden übertragen werden darf.<br>
					  - Für eine kurze, einfache Nachbesichtigung beträgt das Prüfentgelt 3,00 <br>
	<upper>*)</upper> Untersuchung des Motor- und Abgasmanagements (Nachfolge zur AU)<br>
	<upper>**)</upper> mehrspuriges Kraftfahrzeug entsprechend der EU-Richtlinie 2002/24/EG

</div>
<a class="btn btn-default" href="<?php echo $this->url('preise');?>">Zurück</a>
<div style="clear:both;"></div>
<fett>* Alle Untersuchungen und Prüfungen erfolgen im Namen und für Rechnung der GTÜ Gesellschaft für Technische Überwachung mbH, Stuttgart *</fett>