<?php
$title = 'Kosten berechnen';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<a class="btn btn-default" href="<?php echo $this->url('preise',array('action' => 'allepreise'));?>">Alle Preise anzeigen</a>

<div id="priceselection">
	<div id="krad"      class="vehiclebutton" onclick="setVehicle('krad');showHideForm();">Kraftrad</div>
	<div id="pkw"       class="vehiclebutton" onclick="setVehicle('pkw');showHideForm();">Pkw</div>
	<div id="kraftfzg"  class="vehiclebutton" onclick="setVehicle('kraftfzg');showHideForm();">Kraftfahrzeug</div>
	<div id="lof"       class="vehiclebutton" onclick="setVehicle('lof');showHideForm();">Lof</div>
	<div id="anhaenger" class="vehiclebutton" onclick="setVehicle('anhaenger');showHideForm();">Anhänger</div>
	<div style="clear:both;"></div>
	<div id="priceForm">

		<hr>

		<div id="baujahr" class="smallFloatingBox">
			<h3>Baujahr</h3>
			<input onclick="showHideForm();" type="radio" name="baujahr" value="ab89" checked="checked"> ab 1.1.1989<br>
			<input onclick="showHideForm();" type="radio" name="baujahr" value="vor89"> vor 1.1.1989<br>
			<!--input onclick="showHideForm();" type="radio" name="baujahr" value="keineAngabe" checked="checked"> keine Angabe<br-->
		</div>

		<div id="kmh" class="smallFloatingBox">
			<h3>Geschwindigkeit</h3>
			<input onclick="showHideForm();" type="radio" name="kmh" value="bis40" checked="checked"> bis 40 km/h<br>
			<input onclick="showHideForm();" type="radio" name="kmh" value="über40"> über 40 km/h<br>
			<!--input onclick="showHideForm();" type="radio" name="kmh" value="keineAngabe" checked="checked"> keine Angabe<br-->
		</div>

		<div id="bremse" class="smallFloatingBox">
			<h3>Bremse</h3>
			<input onclick="showHideForm();" type="radio" name="bremse" value="ohneB" checked="checked"> ohne Bremse<br>
			<input onclick="showHideForm();" type="radio" name="bremse" value="mitB"> mit Bremse<br>
			<!--input onclick="showHideForm();" type="radio" name="bremse" value="keineAngabe" checked="checked"> keine Angabe<br-->
		</div>

		<div id="dienstleistung" class="smallFloatingBox">
			<h3>Dienstleistung</h3>
			<input onclick="showHideForm();" id="checkHU"        type="checkbox" name="dienstleistung" value="hauptuntersuchung" checked="checked" onclick="showHideForm();"> Hauptuntersuchung<br>
			<div id="checkSPbox"><input onclick="showHideForm();" id="checkSP" type="checkbox" name="dienstleistung" value="sicherheitsprüfung" onclick="showHideForm();"> Sicherheitsprüfung</div>
			<input onclick="showHideForm();" id="checkAenderung" type="checkbox" name="dienstleistung" value="änderungAmFahrzeug"> Änderungen am Fahrzeug<br>
			<input onclick="showHideForm();" id="checkOld"       type="checkbox" name="dienstleistung" value="oldtimerGutachten" onclick="showHideForm();"> Oldtimer-Gutachten<br>
		</div>

		<div id="gewicht" class="smallFloatingBox">
			<h3>Gewicht</h3>
			<div id="gPkw">
				<input type="radio" name="gPkw" value="bis 3,5 t" checked="checked"> bis 3,5 t<br>
				Bei Pkw mit zul. Ges.-Masse üb. 3,5 t gilt das Entgelt der Nfz-Klasse mit zGM >3,5 bis 7,5t
			</div>
			<div id="gKraftfzg">
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value="bis 3,5 t" checked="checked"> bis 3,5 t<br>
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value=">3,5 bis 7,5 t"  > &gt;3,5 bis 7,5 t<br>
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value=">7,5 bis 12,0 t" > &gt;7,5 bis 12,0 t<br>
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value=">12,0 bis 18,0 t"> &gt;12,0 bis 18,0 t<br>
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value=">18,0 bis 28,0 t"> &gt;18,0 bis 28,0 t<br>
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value=">28,0 bis 32,0 t"> &gt;28,0 bis 32,0 t<br>
				<input onclick="showHideForm();" type="radio" name="gKraftfzg" value="über 32,0 t"     > über 32,0 t<br>
			</div>
			<div id="gLof">
				<div id="gLofBis40">
					<input onclick="showHideForm();" type="radio" name="gLofBis40" value="bis 7,5 t" checked="checked"> bis 7,5 t<br>
					<input onclick="showHideForm();" type="radio" name="gLofBis40" value=">7,5 bis 12,0 t"> &gt;7,5 bis 12,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gLofBis40" value="über 12,0 t"    > über 12,0 t<br>
				</div>
				<div id="gLofÜb40">
					<input onclick="showHideForm();" type="radio" name="gLofÜb40" value="bis 7,5 t" checked="checked"> bis 7,5 t<br>
					<input onclick="showHideForm();" type="radio" name="gLofÜb40" value=">7,5 bis 18,0 t" > &gt;7,5 bis 18,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gLofÜb40" value=">18,0 bis 32,0 t"> &gt;18,0 bis 32,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gLofÜb40" value="über 32,0 t"     > über 32,0 t<br>
				</div>
			</div>
			<div id="gAnhaenger">
				<div id="gAnhngrOhneB">
					<input onclick="showHideForm();" type="radio" name="gAnhngrOhneB" value="bis 0,75 t" checked="checked"> bis 0,75 t<br>
				</div>
				<div id="gAnhngrMitB">
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value="bis 3,5 t" checked="checked"> bis 3,5 t<br>
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value=">3,5 bis 7,5 t"  > &gt;3,5 bis 7,5 t<br>
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value=">7,5 bis 12,0 t" > &gt;7,5 bis 12,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value=">12,0 bis 18,0 t"> &gt;12,0 bis 18,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value=">18,0 bis 28,0 t"> &gt;18,0 bis 28,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value=">28,0 bis 32,0 t"> &gt;28,0 bis 32,0 t<br>
					<input onclick="showHideForm();" type="radio" name="gAnhngrMitB" value="über 32,0 t"     > über 32,0 t<br>
				</div>
			</div>
		</div>

		<div id="uma" class="smallFloatingBox">
			<h3>Abgas</h3>
			<input onclick="showHideForm();" type="radio" name="UMA" value="ohneUma" checked="checked"> ohne UMA (UMA liegt vor)<br>
			<input onclick="showHideForm();" type="radio" name="UMA" value="mitUma"> inklusive UMA<br>
			<div id="abgase">
				<input onclick="showHideForm();" type="radio" name="abgas" value="ohneAbgasstrom" checked="checked"> ohne Abgasstrommessung<br>
				<input onclick="showHideForm();" type="radio" name="abgas" value="mitAbgasstrom"> mit Abgasstrommessung<br>
				<!--input type="radio" name="abgas" value="keineAngabe" checked="checked"> keine Angabe -->
			</div>
			<!--input type="radio" name="UMA" value="keineAngabe" checked="checked" onclick="showHideForm();"> keine Angabe -->
		</div>
		<div style="clear:both;"></div>

		<input type="button" class="btn btn-default" value="Preis Berechnen" onclick="calculatePrice('<?php echo $this->url('preise',array('action' => 'preisjson'));?>');">
		

		<div id="pricecalculation">
			<hr>
		</div>
		<div style="clear:both;"></div>
	</div>
</div>

