{
	"krad": {
		"vor89":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftrad', '', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "0,00",
					"mitAbgasstrommessung"  : "0,00"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftrad', '', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftrad', '', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftrad', '', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "0,00",
				"nachuntersuchung" : "0,00"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"          : "<?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'a')['preis']; ?>",
				"mittel"           : "<?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'b')['preis']; ?>",
				"umfangreich"      : "<?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'c')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'd')['preis']; ?>",
				"zuschlag"         : "<?php echo $gtueData->getPreis('aenderung','Kraftrad', '', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftrad', '', 'a')['preis']; ?>",
				"mitUMA"  : "0,00"
			}
		},
		"ab89" : {
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Krad', '', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Krad', '', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Krad', '', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Krad', '', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Krad', '', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Krad', '', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "0,00",
				"nachuntersuchung" : "0,00"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"          : "<?php echo $gtueData->getPreis('aenderung','Krad', '', 'a')['preis']; ?>",
				"mittel"           : "<?php echo $gtueData->getPreis('aenderung','Krad', '', 'b')['preis']; ?>",
				"umfangreich"      : "<?php echo $gtueData->getPreis('aenderung','Krad', '', 'c')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('aenderung','Krad', '', 'd')['preis']; ?>",
				"zuschlag"         : "<?php echo $gtueData->getPreis('aenderung','Krad', '', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Krad', '', 'a')['preis']; ?>",
				"mitUMA"  : "0,00"
			}
		}
	},
	"pkw": {
		"bis 3,5 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','pkw', 'bis 3,5 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','pkw', 'bis 3,5 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','pkw', 'bis 3,5 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','pkw', 'bis 3,5 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','pkw', 'bis 3,5 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','pkw', 'bis 3,5 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "0,00",
				"nachuntersuchung" : "0,00"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','pkw', 'bis 3,5 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','pkw', 'bis 3,5 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','pkw', 'bis 3,5 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','pkw', 'bis 3,5 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','pkw', 'bis 3,5 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','pkw', 'bis 3,5 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','pkw', 'bis 3,5 t', 'b')['preis']; ?>"
			}
		}
	},
	"kraftfzg": {
		"bis 3,5 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'bis 3,5 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'bis 3,5 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'bis 3,5 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'bis 3,5 t', 'b')['preis']; ?>"
			}
		},
		">3,5 bis 7,5 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>3,5 bis 7,5 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>3,5 bis 7,5 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>3,5 bis 7,5 t', 'b')['preis']; ?>"
			}
		},
		">7,5 bis 12,0 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>7,5 bis 12,0 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>7,5 bis 12,0 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>7,5 bis 12,0 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>7,5 bis 12,0 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>7,5 bis 12,0 t', 'b')['preis']; ?>"
			}
		},
		">12,0 bis 18,0 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>12,0 bis 18,0 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>12,0 bis 18,0 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>12,0 bis 18,0 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>12,0 bis 18,0 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>12,0 bis 18,0 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>12,0 bis 18,0 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>12,0 bis 18,0 t', 'b')['preis']; ?>"
			}
		},
		">18,0 bis 28,0 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>18,0 bis 28,0 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>18,0 bis 28,0 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>18,0 bis 28,0 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>18,0 bis 28,0 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>18,0 bis 28,0 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>18,0 bis 28,0 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>18,0 bis 28,0 t', 'b')['preis']; ?>"
			}
		},
		">28,0 bis 32,0 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', '>28,0 bis 32,0 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', '>28,0 bis 32,0 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>28,0 bis 32,0 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>28,0 bis 32,0 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>28,0 bis 32,0 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', '>28,0 bis 32,0 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', '>28,0 bis 32,0 t', 'b')['preis']; ?>"
			}
		},
		"über 32,0 t":{
			"hauptuntersuchung":{
				"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?>",
				"mitUMA" : {
					"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'b')['preis']; ?>",
					"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'c')['preis']; ?>"
				},
				"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'd')['preis']; ?>",
				"nachkontrolle" : {
					"einfach"    : "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'e')['preis']; ?>",
					"umfangreich": "<?php echo $gtueData->getPreis('hu','Kraftfahrzeug', 'über 32,0 t', 'f')['preis']; ?>"
				}
			},
			"sicherheitspruefung" : {
				"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?>",
				"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Kraftfahrzeug', 'über 32,0 t', 'b')['preis']; ?>"
			},
			"aenderungenAmFahrzeug" : {
				"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?>",
				"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'über 32,0 t', 'b')['preis']; ?>",
				"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'über 32,0 t', 'c')['preis']; ?>",
				"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'über 32,0 t', 'd')['preis']; ?>",
				"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Kraftfahrzeug', 'über 32,0 t', 'e')['preis']; ?>"
			},
			"oldtimergutachten" : {
				"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'über 32,0 t', 'a')['preis']; ?>",
				"mitUMA"  : "<?php echo $gtueData->getPreis('oldtimer','Kraftfahrzeug', 'über 32,0 t', 'b')['preis']; ?>"
			}
		}
	},
	"lof": {
		"bis40":{
			"bis 7,5 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM bis 40 km/h', 'bis 7,5 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">7,5 bis 12,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM bis 40 km/h', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			"über 12,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM bis 40 km/h', 'über 12,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			}
		},
		"über40":{
			"bis 7,5 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', 'bis 7,5 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">7,5 bis 18,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', '>7,5 bis 18,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">18,0 bis 32,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', '>18,0 bis 32,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			"über 32,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Lof.-ZM ueber 40 km/h', 'über 32,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			}
		}
	},
	"anhaenger": {
		"ohneB":{
			"bis 0,75 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger ohne Bremse', 'bis 0,75 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger ohne Bremse', 'bis 0,75 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger ohne Bremse', 'bis 0,75 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger ohne Bremse', 'bis 0,75 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger ohne Bremse', 'bis 0,75 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			}
		},
		"mitB":{
			"bis 3,5 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'bis 3,5 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'bis 3,5 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'bis 3,5 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'bis 3,5 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', 'bis 3,5 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">3,5 bis 7,5 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "0,00",
					"nachuntersuchung" : "0,00"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>3,5 bis 7,5 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">7,5 bis 12,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "0,00",
						"mitAbgasstrommessung"  : "0,00"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>7,5 bis 12,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">12,0 bis 18,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
						"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'b')['preis']; ?>"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>12,0 bis 18,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">18,0 bis 28,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
						"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'b')['preis']; ?>"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>18,0 bis 28,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			">28,0 bis 32,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
						"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'b')['preis']; ?>"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', '>28,0 bis 32,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			},
			"über 32,0 t":{
				"hauptuntersuchung":{
					"ohneUMA" : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?>",
					"mitUMA" : {
						"ohneAbgasstrommessung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?>",
						"mitAbgasstrommessung"  : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', 'über 32,0 t', 'b')['preis']; ?>"
					},
					"nachuntersuchung": "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'über 32,0 t', 'd')['preis']; ?>",
					"nachkontrolle" : {
						"einfach"    : "<?php echo $gtueData->getPreis('hu','Anhaenger mit Bremse', 'über 32,0 t', 'm')['preis']; ?>",
						"umfangreich": "0,00"
					}
				},
				"sicherheitspruefung" : {
					"erstuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?>",
					"nachuntersuchung" : "<?php echo $gtueData->getPreis('sp','Anhaenger mit Bremse', 'über 32,0 t', 'b')['preis']; ?>"
				},
				"aenderungenAmFahrzeug" : {
					"einfach"         :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?>",
					"mittel"          :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'über 32,0 t', 'b')['preis']; ?>",
					"umfangreich"     :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'über 32,0 t', 'c')['preis']; ?>",
					"nachuntersuchung":"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'über 32,0 t', 'd')['preis']; ?>",
					"zuschlag"        :"<?php echo $gtueData->getPreis('aenderung','Anhaenger mit Bremse', 'über 32,0 t', 'e')['preis']; ?>"
				},
				"oldtimergutachten" : {
					"ohneUMA" : "<?php echo $gtueData->getPreis('oldtimer','Anhaenger mit Bremse', 'über 32,0 t', 'a')['preis']; ?>",
					"mitUMA"  : "0,00"
				}
			}
		}
	}
}